In [1]:
import numpy as np
import scipy.linalg as lin

In [2]:
a = np.array([[1, 2], [3, 4]])
inv_a = lin.inv(a)
inv_a

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [5]:
b = np.array([[5, 6], [7, 8]])
c = a + b
c

array([[ 6,  8],
       [10, 12]])

In [6]:
b1 = (-1)*np.ones((4, ), dtype=np.float64)
b2 = 2*np.ones((5, ), dtype=np.float64)
b3 = np.ones((4, ), dtype=np.float64)

A = np.diag(b1, k=-1) + np.diag(b2, k=0) + np.diag(b3, k=1)
A

array([[ 2.,  1.,  0.,  0.,  0.],
       [-1.,  2.,  1.,  0.,  0.],
       [ 0., -1.,  2.,  1.,  0.],
       [ 0.,  0., -1.,  2.,  1.],
       [ 0.,  0.,  0., -1.,  2.]])

In [7]:
r = 3
res1 = a + r
res2 = b + r

res1

array([[4, 5],
       [6, 7]])

In [8]:
res2

array([[ 8,  9],
       [10, 11]])

In [9]:
res3 = a * b
res3

array([[ 5, 12],
       [21, 32]])

In [11]:
res4 = a / b
res4

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [12]:
res5 = b / a
res5

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [13]:
res6 = a@b
res6

array([[19, 22],
       [43, 50]])

In [14]:
res7 = b@a
res7

array([[23, 34],
       [31, 46]])

In [15]:
c = np.array([2, 4])
res8 = a * c
res8 

array([[ 2,  8],
       [ 6, 16]])

In [21]:
a.shape[1]

2

In [20]:
c.shape[0]

2

In [22]:
res9 = c * a
res9

array([[ 2,  8],
       [ 6, 16]])