In [1]:
import pandas as pd
import numpy as np

In [2]:
a = np.random.randint(0, 10, 24).reshape(4,6)
df = pd. DataFrame(a, index=list("가나다라"), columns=list("ABCDEF"))
df

A  B  C  D  E  F
가  4  7  8  3  8  8
나  2  3  3  9  4  0
다  3  1  9  4  6  0
라  4  9  0  1  2  4

In [3]:
random_numbers = np.random.randint(1, 10, size=20)
print(random_numbers)

[4 6 8 3 8 8 8 5 6 4 9 3 1 3 5 4 5 5 5 1]


In [4]:
import random

# 일정 범위 내에서 중복을 허용하지 않고 숫자를 고르기
num_list = random.sample(range(0, 10), 10)  # 1부터 100 사이에서 10개의 숫자를 무작위로 선택하여 리스트로 만듦

print(num_list)  # 선택된 숫자들을 출력


[1, 0, 6, 2, 5, 3, 8, 7, 9, 4]


In [5]:
np.random.choice(5,3, p=[0.1, 0.1, 0.5, 0.1, 0.2])


array([3, 3, 4])

In [6]:
np.random.choice(5, 3, replace=False)

array([2, 3, 1])

In [7]:
a

array([[4, 7, 8, 3, 8, 8],
       [2, 3, 3, 9, 4, 0],
       [3, 1, 9, 4, 6, 0],
       [4, 9, 0, 1, 2, 4]])

In [8]:
df

A  B  C  D  E  F
가  4  7  8  3  8  8
나  2  3  3  9  4  0
다  3  1  9  4  6  0
라  4  9  0  1  2  4

In [9]:
type(df["A"])

pandas.core.series.Series

In [10]:
df["A"].shape

(4,)

In [11]:
df["A"].values

array([4, 2, 3, 4])

In [12]:
np.array([1, 2, 3, 4]).T.shape

(4,)

In [13]:
type(df[["A", "C", "E"]])

pandas.core.frame.DataFrame

In [14]:
df[["A", "C", "E"]].T.shape

(3, 4)

In [15]:
df[["A", "C", "E"]].T.index

Index(['A', 'C', 'E'], dtype='object')

In [16]:
df[["A", "C", "E"]].T.columns

Index(['가', '나', '다', '라'], dtype='object')

In [17]:
# .loc[...] 개별적인 복수를 선택하기 위해 리스트[]를 쓰거나, 연속하는 일부를 선택하기 위해 slicing을 쓰거나 할 수 있다.🌺 
df.loc[["나","가"], "B":"E"]

B  C  D  E
나  3  3  9  4
가  7  8  3  8

In [18]:
df.iloc[[1, 0, 2], :3]

A  B  C
나  2  3  3
가  4  7  8
다  3  1  9

In [19]:
df.drop("D", axis=1)

A  B  C  E  F
가  4  7  8  8  8
나  2  3  3  4  0
다  3  1  9  6  0
라  4  9  0  2  4